# Generated by Django 5.2.5 on 2025-08-19 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'A fazer'), ('doing', 'Em andamento'), ('done', 'Concluído')], default='todo', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='tags.tag')),
            ],
        ),
    ]
